apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizard-api
  namespace: sre
spec:
  ingressClassName: nginx
  rules:
  - host: wizard-api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wizard-api
            port:
              number: 80
